### ISSUE TITLE
The datasets update

### ISSUE THREAD

**Issue by miharbi1982** [RamiKrispin/coronavirus#39]
Hi Rami;
When I runing the "update_datasets" I get the following error message: Error in update_datasets() : could not find function "update_datasets".
And if I want to install the package I get the following error message : Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
there is no package called ‘fs’.
What is the problem, please?

**Comment by olivermills** [comment]
I'm also getting this error

**Comment by miharbi1982** [comment]
The problem has been resolved.
Use : devtools::install_github("RamiKrispin/coronavirus"). You will find ’fs’ package, then complete the execution.

**Comment by RamiKrispin** [comment]
Thanks @miharbi1982, @olivermills still have an issue with the installation?
For some reason, something when installing packages from Github it fails to install some of the dependencies packages. One way to solve it is to install separately those packages and then reinstall the package from Github

**Comment by RamiKrispin** [comment]
@miharbi1982 , @olivermills do you still having a problem with the `update_dataset` function?

**Comment by miharbi1982** [comment]
No, It's fixed.
Thanks, @RamiKrispin for your efforts.
